modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/unilock/ArborealAscent/issues"

[[mods]]
modId = "arborealascent"
version = "${version}"
displayName = "Arboreal Ascent"
displayURL = "https://github.com/unilock/ArborealAscent"
authors = "unilock"
description = '''Climb trees!'''
logoFile = "icon.png"

[[dependencies.arborealascent]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
