# Gradle Properties
org.gradle.jvmargs=-Xmx2G

# Architectury Properties
minecraft_version=1.21.1
parchment_mappings=2024.11.17
enabled_platforms=fabric,neoforge
fabric_loader_version=0.17.2
neoforge_version=21.1.209

# Mod Properties
mod_version=2.1.0
maven_group=cc.unilock
archives_base_name=ArborealAscent
